name: Full CI/CD Pipeline with Artifact and Branch Logic

on:
  push:
    branches: [master, production]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: write  # Needed to publish GitHub releases

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build step
        run: |
          mkdir -p output
          echo "Built on ${{ matrix.os }} by Sahil Thakur" > output/build_info.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: output/
          retention-days: 14

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v4
        with:
          name: build-ubuntu-latest
          path: ./artifact

      - name: Run test step
        run: |
          echo "Running tests using artifact:"
          cat ./artifact/build_info.txt

  release:
    name: Create GitHub Release (only on master)
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-ubuntu-latest
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Release automatically generated from master.
          files: ./release/build_info.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to Production (only on production)
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dummy deploy step
        run: |
          echo "Deploying to production..."
          echo "Production deployment done by Sahil Thakur."
