name: Test GitHub Secrets

on: [push]

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print masked secret
        run: echo "This is secret key of sahil: ${{ secrets.FAKE_API_KEY }}"

