name: Variable Scope Demo of Sahil Thakur - new

on: [push]

env:
  MY_VARIABLE: "Defined at workflow level"

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "Overridden at job level"

    steps:
      - name: Step 1 - Inherit from Job
        run: echo "MY_VARIABLE = $MY_VARIABLE"

      - name: Step 2 - Override at Step Level
        env:
          MY_VARIABLE: "Overridden at step level"
        run: echo "MY_VARIABLE = $MY_VARIABLE"

      - name: Step 3 - Back to Job Level
        run: echo "MY_VARIABLE = $MY_VARIABLE"
